2022-02-28 10:10:01 [INFO   ][ln-256]: Test test_post_headers_body_json passed.
2022-02-28 10:10:01 [INFO   ][ln-290]: Test test_post_normal_body passed.
2022-02-28 10:10:01 [INFO   ][ln-297]: Calling test_get_auth_httpbin.
2022-02-28 10:10:02 [INFO   ][ln-305]: Test test_get_auth_httpbin passed.
2022-02-28 10:10:02 [INFO   ][ln-319]: Calling test_mock_service.
2022-02-28 10:10:02 [ERROR  ][ln-398]: requests.get() failed with exception: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /hello (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f70113a4c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-02-28 10:10:02 [INFO   ][ln-335]: Calling test_mock_service_dynamic.
2022-02-28 10:10:02 [ERROR  ][ln-398]: requests.get() failed with exception: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /anyendpoint (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f70113bc150>: Failed to establish a new connection: [Errno 111] Connection refused'))
