2022-03-04 09:40:43 [INFO   ][ln-256]: Test test_post_headers_body_json passed.
2022-03-04 09:40:44 [INFO   ][ln-290]: Test test_post_normal_body passed.
2022-03-04 09:40:44 [INFO   ][ln-297]: Calling test_get_auth_httpbin.
2022-03-04 09:40:45 [INFO   ][ln-305]: Test test_get_auth_httpbin passed.
2022-03-04 09:40:45 [INFO   ][ln-319]: Calling test_mock_service.
2022-03-04 09:40:45 [ERROR  ][ln-415]: requests.get() failed with exception: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /hello (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0d490b1048>: Failed to establish a new connection: [Errno 111] Connection refused',))
2022-03-04 09:40:45 [INFO   ][ln-335]: Calling test_mock_service_dynamic.
2022-03-04 09:40:45 [ERROR  ][ln-415]: requests.get() failed with exception: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /anyendpoint (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0d487444e0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2022-03-04 09:40:45 [INFO   ][ln-365]: Test test_by_input_text passed.
